[build-system]
requires = ["uv_build>=0.7.20,<0.8.0"]
build-backend = "uv_build"

[project]
name = "pyrb"
version = "1.0.1"
description = "pyrb is a Python library to solve constrained risk budgeting problem."
readme = "README.md"
authors = [
    {name = "Jean-Charles Richard", email = "jcharles.richard@gmail.com"}
]
license = "Apache-2.0"
requires-python = ">=3.12"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Financial and Insurance Industry",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Office/Business :: Financial",
    "Topic :: Scientific/Engineering :: Mathematics",
]
dependencies = [
    "pandas>=2.0.0",
    "numba>=0.58.0",
    "quadprog>=0.1.0",
    "scipy>=1.10.0",
    "numpy>=1.24.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "ruff>=0.12.2",
]
